### ISSUE TITLE
FIXME: Crash when trying to set game path with graphical file picker

### ISSUE THREAD

**Issue by MrKorner** [RimSort/RimSort#182] opened 2023-10-09 14:38 UTC
**Describe the bug**
Upon trying to set a game path using graphical file picker (the button with 3 dots next to path text box)

**To Reproduce**
1. click on `'...' button next to game directory path text box
2. See error

**Expected behavior**
Graphical file picker opens to let me pick of game directory (or any other entries).

**Please complete the following information:**
 - OS: Gentoo Linux 
 - RimSort version: a-1.62.2-hf
 - Please provide a `RimSort.log`:
 This is all the output there is to be had:

```
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

 - Are you running from Python interpreter or from a compiled RimSort release?
 Compiled Binary

**Additional context**

This problem arises from `libgdk_pixbuf-2.0.so.0` library expecting  gdk-pixbuf on the system be built with png loader being built as separate library, upstream it is by [default](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/blob/master/meson_options.txt#L17) built to be merged with jpeg loader.
 
Problem can be temporarily solved by removing gdk pixbuf library from precompiled binary which will force RimSort to use system one which will now work properly and nothing will crash.

**Comment by parona-source** [comment] 2023-10-09 14:52
Of debian version bullseye old enough that png and jpeg aren't built-in https://packages.debian.org/bullseye/amd64/libgdk-pixbuf-2.0-0/filelist.

This issue could be addressed by either including the loader libraries and setting GDK_PIXBUF_MODULEDIR to point to that location or even updating to bookworm https://packages.debian.org/bookworm/amd64/libgdk-pixbuf-2.0-0/filelist which builds in png. Updating to bookworm of course would drop support for older distribution releases.

**Comment by andoruB** [comment] 2024-02-14 17:20
The same error shows up for me as well: 

```
Gtk-Message: 18:57:55.693: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:57:55.693: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:57:55.693: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:57:55.693: Failed to load module "canberra-gtk-module"
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[2024-02-14 18:57:57] WARNING: Essential path(s) not set!

(RimSort.bin:67504): Gtk-WARNING **: 18:57:59.601: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
```

Log: 
```
[DEBUG][2024-02-14 18:50:06][66889][root][setup_logging][220] : _________________New log started__________________
[DEBUG][2024-02-14 18:50:06][66889][root][setup_logging][221] : Log config file: /opt/rimsort/data/logger_tt-DEBUG.json
[DEBUG][2024-02-14 18:50:06][66889][root][_replace_with_queue_handler][138] : Logging queue listener started!
[DEBUG][2024-02-14 18:50:06][66889][__main__][<module>][359] : Running using Nuitka bundle
[DEBUG][2024-02-14 18:50:06][66889][__main__][<module>][368] : Initializing RimSort application
[DEBUG][2024-02-14 18:50:06][66889][__main__][main_thread][242] : Setting application style
[INFO][2024-02-14 18:50:06][66889][__main__][__init__][92] : Initializing MainWindow
[DEBUG][2024-02-14 18:50:06][66889][view.game_configuration_panel][__init__][52] : Initializing GameConfiguration
[DEBUG][2024-02-14 18:50:07][66889][window.settings_panel][__init__][38] : Initializing SettingsPanel
[DEBUG][2024-02-14 18:50:07][66889][window.settings_panel][__init__][448] : Finished SettingsPanel initialization
[INFO][2024-02-14 18:50:07][66889][view.game_configuration_panel][_initialize_storage][524] : Initializing storage
[INFO][2024-02-14 18:50:07][66889][view.game_configuration_panel][_initialize_storage][525] : Determined storage path: /root/.local/share/RimSort
[INFO][2024-02-14 18:50:07][66889][view.game_configuration_panel][_initialize_storage][528] : Storage path [/root/.local/share/RimSort] does not exist
[INFO][2024-02-14 18:50:07][66889][model.dialogue][show_information][120] : Showing information box with input: [Welcome], [Welcome to RimSort!], [It looks like you may be running RimSort for the first time! RimSort stores some client information in this directory:
[/root/.local/share/RimSort].
It doesn't look like this directory exists, so we'll make it for you now.], [None]
[DEBUG][2024-02-14 18:50:07][66889][model.dialogue][show_information][142] : Finished showing information box
[INFO][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][537] : Making storage directory
[INFO][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][544] : Determined dbs path: /root/.local/share/RimSort/dbs
[INFO][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][555] : Determined settings file path: /root/.local/share/RimSort/settings.json
[INFO][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][557] : Settings file does not exist!
[INFO][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][578] : Writing default settings to: /root/.local/share/RimSort/settings.json
[INFO][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][583] : Settings file exists!
[DEBUG][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][586] : Loaded JSON from file!
[INFO][2024-02-14 18:50:11][66889][view.game_configuration_panel][_initialize_storage][751] : Finished storage initialization
[DEBUG][2024-02-14 18:50:11][66889][view.game_configuration_panel][__init__][448] : Finished GameConfiguration initialization
[DEBUG][2024-02-14 18:50:11][66889][view.main_content_panel][__init__][116] : Initializing MainContent
[INFO][2024-02-14 18:50:11][66889][view.main_content_panel][__init__][123] : Loading GameConfiguration instance
[DEBUG][2024-02-14 18:50:11][66889][sub_view.mod_info_panel][__init__][26] : Initializing ModInfo
[DEBUG][2024-02-14 18:50:11][66889][model.scroll_label][__init__][18] : Initializing ScrollLabel
[DEBUG][2024-02-14 18:50:11][66889][model.scroll_label][__init__][49] : Finished ScrollLabel initialization
[DEBUG][2024-02-14 18:50:11][66889][sub_view.mod_info_panel][__init__][159] : Finished ModInfo initialization
[DEBUG][2024-02-14 18:50:11][66889][sub_view.active_mods_panel][__init__][40] : Initializing ActiveModList
[DEBUG][2024-02-14 18:50:11][66889][model.mod_list][__init__][57] : Initializing ModListWidget
[DEBUG][2024-02-14 18:50:11][66889][model.mod_list][__init__][141] : Finished ModListWidget initialization
[DEBUG][2024-02-14 18:50:11][66889][sub_view.active_mods_panel][__init__][192] : Finished ActiveModList initialization
[DEBUG][2024-02-14 18:50:11][66889][sub_view.inactive_mods_panel][__init__][34] : Initializing InactiveModList
[DEBUG][2024-02-14 18:50:11][66889][model.mod_list][__init__][57] : Initializing ModListWidget
[DEBUG][2024-02-14 18:50:11][66889][model.mod_list][__init__][141] : Finished ModListWidget initialization
[DEBUG][2024-02-14 18:50:11][66889][sub_view.inactive_mods_panel][__init__][147] : Finished InactiveModList initialization
[DEBUG][2024-02-14 18:50:11][66889][sub_view.actions_panel][__init__][35] : Initializing Actions
[DEBUG][2024-02-14 18:50:11][66889][sub_view.actions_panel][__init__][241] : Finished Actions initialization
[DEBUG][2024-02-14 18:50:11][66889][util.steam.steamcmd.wrapper][__init__][30] : Initializing SteamcmdInterface
[DEBUG][2024-02-14 18:50:11][66889][util.steam.steamcmd.wrapper][__init__][66] : SteamCMD does not exist. Creating path for installation: /root/.local/share/RimSort/steamcmd
[DEBUG][2024-02-14 18:50:11][66889][util.steam.steamcmd.wrapper][__init__][89] : Finished SteamcmdInterface initialization
[INFO][2024-02-14 18:50:11][66889][view.main_content_panel][__init__][251] : Finished MainContent initialization
[INFO][2024-02-14 18:50:11][66889][view.status_panel][__init__][19] : Initializing Status
[DEBUG][2024-02-14 18:50:11][66889][view.status_panel][__init__][39] : Finished Status initialization
[DEBUG][2024-02-14 18:50:11][66889][__main__][__init__][143] : Finished MainWindow initialization
[INFO][2024-02-14 18:50:11][66889][__main__][main_thread][251] : Showing MainWindow
[INFO][2024-02-14 18:50:11][66889][view.main_content_panel][actions_slot][804] : USER ACTION: received action check_for_update
[DEBUG][2024-02-14 18:50:11][66889][view.main_content_panel][_do_check_for_update][984] : Checking for RimSort update...
[DEBUG][2024-02-14 18:50:11][66889][view.main_content_panel][_do_check_for_update][996] : Current RimSort release found: alpha-v1.0.6.2-hf
[DEBUG][2024-02-14 18:50:11][66889][view.main_content_panel][_do_check_for_update][997] : Current RimSort version found: alpha-v1.0.6.2-hf
[DEBUG][2024-02-14 18:50:11][66889][view.main_content_panel][_do_check_for_update][1162] : Up to date!
[INFO][2024-02-14 18:50:11][66889][model.dialogue][show_information][120] : Showing information box with input: [RimSort is up to date!], [You are already running the latest release: alpha-v1.0.6.2-hf], [None], [None]
[DEBUG][2024-02-14 18:50:11][66889][model.dialogue][show_information][142] : Finished showing information box
[DEBUG][2024-02-14 18:50:13][66889][view.game_configuration_panel][check_if_essential_paths_are_set][1064] : Game folder: 
[DEBUG][2024-02-14 18:50:13][66889][view.game_configuration_panel][check_if_essential_paths_are_set][1065] : Config folder: 
[WARNING][2024-02-14 18:50:13][66889][view.game_configuration_panel][check_if_essential_paths_are_set][1067] : Essential path(s) not set!
[INFO][2024-02-14 18:50:13][66889][model.dialogue][show_warning][159] : Showing warning box with input: [None], [Essential path(s) not set!], [RimSort requires, at the minimum, for the game install folder and the config folder paths to be set. Please set both these either manually or by using the AutoDetect functionality.], [None]
[DEBUG][2024-02-14 18:50:13][66889][model.dialogue][show_warning][181] : Finished showing warning box
[INFO][2024-02-14 18:50:14][66889][view.main_content_panel][__insert_data_into_lists][373] : Inserting mod data into active [0] and inactive [0] mod lists
[INFO][2024-02-14 18:50:14][66889][model.mod_list][recreate_mod_list][1054] : Internally recreating active mod list
[INFO][2024-02-14 18:50:14][66889][model.mod_list][recreate_mod_list][1054] : Internally recreating inactive mod list
[INFO][2024-02-14 18:50:14][66889][view.main_content_panel][__insert_data_into_lists][383] : Finished inserting mod data into active [0] and inactive [0] mod lists
[DEBUG][2024-02-14 18:50:14][66889][view.main_content_panel][_do_refresh][1326] : Essential paths have not been set. Passing refresh and resetting mod lists
[INFO][2024-02-14 18:50:14][66889][__main__][__initialize_watchdog][193] : Initializing watchdog FS Observer
[INFO][2024-02-14 18:50:15][66889][view.game_configuration_panel][set_game_exe_folder][1158] : USER ACTION: set the game install folder
```

`export GDK_PIXBUF_MODULEDIR=/usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders` also doesn't fix the issue for me

I'm using Manjaro XFCE

Luckly there's still rmm that works fine, just that a GUI would've been better

**Comment by Chunnyluny** [comment] 2024-04-27 15:09
@andoruB @wizel10 @parona-source @MrKorner Will be fixed in another overall effort for Linux compatibility. Closing as duplicate of #35

**Closed by Chunnyluny** 2024-04-27 15:09 UTC
Labels: bugs 🪲, Linux🐧
