### ISSUE TITLE
FIXME: "Toggle warning" on version mismatch does not get saved when relaunching the application

### ISSUE THREAD

**Issue by Hibanan** [RimSort/RimSort#535] opened 2024-07-26 13:23 UTC
**Describe the bug:**
When toggling the warning for a mod which is not compatible with the game version, restarting the application causes the toggle to not save and the "version mismatch" warning to display again.

**To Reproduce:**
Toggle warning on a mod with a version mismatch, save the config, relaunch the application.

**Expected behavior:**
Warning stays disabled after relaunching

**Screenshots:**
N/A

**Please complete the following information:**

- Operating System: Win 11 23H2 (22631.3155)
- Processor Architecture: x86
- RimSort version: 1.0.9
- Please provide a `RimSort.log`: http://0x0.st/XfmI.log
- Are you running from the Python interpreter or from a compiled RimSort release? Compiled release for win (RimSort-v1.0.9-Windows_x86_64.zip)
- If this is a sorting issue, what sort mode are you using?: Alphabetical

**Additional context:**
N/A

**Checklist before opening issue:**

- Did you check the wiki for a solution? (macOS Gatekeeper workaround is there) Y
- Did you make sure this issue wasn't already reported? Y

**Comment by hk21702** [comment] 2024-08-20 01:47
Duplicate of #143.

Please continue discussions there.

**Closed by hk21702** 2024-08-20 01:47 UTC
Labels: bugs 🪲, duplicate/existing
