### ISSUE TITLE
Suggestion: A way to color mods

### ISSUE THREAD

**Issue by Hope-Caldwell** [RimSort/RimSort#543] opened 2024-07-30 18:05 UTC
Problem:
Difficulties in debugging large modlists 
I have an about 600 mod modlist, and it is currently very hard to single out a mod that is causing issues using rimsort because of the inability to distinguish mods quickly via color.

Solution:
Adding a way to color mods.
Adding a way to quickly and easily distinguish between mods.

**Comment by hk21702** [comment] 2024-08-19 04:05
Blocked by #403 though likely will not in of itself be implemented in #403

**Comment by Limfjorden** [comment] 2024-10-04 14:25
This issue is a duplicate of https://github.com/RimSort/RimSort/issues/109

**Comment by hk21702** [comment] 2024-10-05 03:00
Closing since duplicate. Please continue discussions in relevant issue.

**Closed by hk21702** 2024-10-05 03:00 UTC
Labels: duplicate/existing, feature/improvement 🆕
