### ISSUE TITLE
FIXME: Crash when trying to set any game path

### ISSUE THREAD

**Issue by tDegan** [RimSort/RimSort#165] opened 2023-09-17 08:56 UTC
**Describe the bug**

**To Reproduce**
1. In the row "Game Folder", click on the button "..."
2. RimSort crashes

**Expected behavior**
Some sort of file dialog opening

**Screenshots**

**Please complete the following information:**
 - OS: Endevaour OS (Arch Linux variant)
 - RimSort version: alpha-v1.0.6.2-hf, happens both for the version from AUR and Github)
 - Please provide a `RimSort.log`: Cannot find the log and the upload function just freezes the window. But here's the console output: [rs.log](https://github.com/RimSort/RimSort/files/12642427/rs.log)
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled.

**Additional context**
Cannot use auto detect, since I have a nonstandard install location

**Comment by twstagg** [comment] 2023-11-26 19:35
@tDegan Hello

Are you having this issue with current Edge build?

**Comment by tDegan** [comment] 2023-11-26 19:54
In the current edge build the "Choose..." button works.

However, the "Open..." button next to it does nothing and just prints 

```
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_trim_arg_from_keyseq
```

to the terminal.

**Comment by twstagg** [comment] 2024-04-27 00:27
Hi @tDegan sorry for the delay

Is this still an issue for you?

**Comment by tDegan** [comment] 2024-04-27 13:39
Yes, I'm still getting the exact same behavior.

**Comment by Chunnyluny** [comment] 2024-04-27 15:06
@tDegan Will be fixed in another overall effort for Linux compatibility. Closing as duplicate of #35"

**Closed by Chunnyluny** 2024-04-27 15:06 UTC
Labels: bugs 🪲, Linux🐧
