### ISSUE TITLE
FIXME: Linux reporting missing libstdc++.so.6 when running todds

### ISSUE THREAD

**Issue by lisanhu** [RimSort/RimSort#248] opened 2024-01-08 03:14 UTC
**Describe the bug**
I'm running it on Pop!_OS 22.04 LTS x86_64. When I tried to optimize the textures, the window shows the following error message:
```
/home/lisanhu/mine/program/RimSort/todds/todds: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/lisanhu/mine/program/RimSort/todds/todds)

/home/lisanhu/mine/program/RimSort/todds/todds: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /home/lisanhu/mine/program/RimSort/todds/todds)
```
![image](https://github.com/RimSort/RimSort/assets/3086096/881ddfde-853f-4523-83fa-a2cfad2fbca9)

**To Reproduce**
1. Click on the "Optimize textures" button on the right

**Expected behavior**
I haven't seen what the expected output yet.

**Screenshots**
As shown above

**Please complete the following information:**
 - OS: Pop!_OS 22.04 LTS x86_64
 - RimSort version: Edge 57d060a
 - Please provide a `RimSort.log`: http://0x0.st/HIzn.log
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled release

**Additional context**
Running `ldconfig -p | grep libstdc++`, I got this:
```
 ~ $ ldconfig -p | grep libstdc++
	libstdc++.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libstdc++.so.6
	libstdc++.so.6 (libc6) => /lib/i386-linux-gnu/libstdc++.so.6
```
So the files are there, but the ABI are different. I would suggest to include a static compiled version of todds.

**Comment by lisanhu** [comment] 2024-01-13 01:45
I have found this closed issue with todds about this problem:
https://github.com/todds-encoder/todds/issues/38

I hope it will help fix it. Thanks!

**Comment by Chunnyluny** [comment] 2024-04-27 15:15
@lisanhu Will be fixed in another overall effort for Linux compatibility. Closing as duplicate of #35

**Closed by Chunnyluny** 2024-04-27 15:15 UTC
Labels: bugs 🪲, Linux🐧, third party 📲

**Comment by twstagg** [comment] 2024-04-27 15:21
To add - todds issues will be handled in #38, this is just being closed as it is related to the overall issue with us freezing the app
