### ISSUE TITLE
FIXME: bad and destructive git clone

### ISSUE THREAD

**Issue by Official-Husko** [RimSort/RimSort#281] opened 2024-04-02 15:32 UTC
**Describe the bug**
When i use "Add git mods" it deletes all files and folders in the rimworld mods folder and then throws the loose files from the target git repository in there.

**To Reproduce**
1. Click on "Add git mods"
2. enter `https://gitgud.io/Ed86/rjw`
3. observe the contents of the mod folder getting nuked and replaced with loose mod files

**Expected behavior**
it should create a mod folder using the repo name with the files inside.

**Please complete the following information:**
 - OS: Windows 11
 - RimSort version: Alpha 1.0.6.2-hf
 - Please provide a `RimSort.log`: already gone sorry
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled

**Comment by Chunnyluny** [comment] 2024-04-05 19:20
Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish
It will then also update if the repo gets updated on github. you can also find your old rimsort log too,  which you can find in the upload logbutton/settingsbutton rimsort.old

**Comment by Official-Husko** [comment] 2024-04-05 21:35
> Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish It will then also update if the repo gets updated on github. you can also find your old rimsort log too, which you can find in the upload logbutton/settingsbutton rimsort.old

1. I do have git.exe. 
2. Requiring Edge seems like a weird thing but i should have the latest webview which i guess is what it needs specifically. 
3. I can only use GitHub links or did i understand that wrong?

**Comment by Chunnyluny** [comment] 2024-04-05 21:59
> > Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish It will then also update if the repo gets updated on github. you can also find your old rimsort log too, which you can find in the upload logbutton/settingsbutton rimsort.old
> 
> 1. I do have git.exe. 
> 2. Requiring Edge seems like a weird thing but i should have the latest webview which i guess is what it needs specifically. 
> 3. I can only use GitHub links or did i understand that wrong?

- 1 okay that is good 
- 2 you misunderstood so I edited. I didn't mean Microsoft edge I mean edge build which is a prerelease term which is used in GitHub releases.
- 3 GitHub links idk about gitgud or gitbucket or anything beyond GitHub

**Comment by Official-Husko** [comment] 2024-04-05 22:33
> > > Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish It will then also update if the repo gets updated on github. you can also find your old rimsort log too, which you can find in the upload logbutton/settingsbutton rimsort.old
> > 
> > 
> > 
> > 1. I do have git.exe.
> > 2. Requiring Edge seems like a weird thing but i should have the latest webview which i guess is what it needs specifically.
> > 3. I can only use GitHub links or did i understand that wrong?
> 
>     * 1 okay that is good
> 
>     * 2 you misunderstood so I edited. I didn't mean Microsoft edge I mean edge build which is a prerelease term which is used in GitHub releases.
> 
>     * 3 GitHub links idk about gitgud or gitbucket or anything beyond GitHub

2. Thank you for clarifying. I did think it was edge.
3. Normally from my understanding git works universally like that if im not wrong. When i use git clone in the cmd for example which i do since i update git mods using a bat file i get a folder like it should be.

Either way i will give the edge build a test run then to see if it solved the issue. Thank you for the help until now.

**Comment by Official-Husko** [comment] 2024-04-06 13:51
> > > Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish It will then also update if the repo gets updated on github. you can also find your old rimsort log too, which you can find in the upload logbutton/settingsbutton rimsort.old
> > 
> > 
> > 
> > 1. I do have git.exe.
> > 2. Requiring Edge seems like a weird thing but i should have the latest webview which i guess is what it needs specifically.
> > 3. I can only use GitHub links or did i understand that wrong?
> 
>     * 1 okay that is good
> 
>     * 2 you misunderstood so I edited. I didn't mean Microsoft edge I mean edge build which is a prerelease term which is used in GitHub releases.
> 
>     * 3 GitHub links idk about gitgud or gitbucket or anything beyond GitHub

Here is what i can report right now after trying the edge build.

1. RimWorld completely refuses to start up. Clicking run game does nothing while working on the latest stable release.
2. Using the Database Builder Crashes on both edge and stable.

[latest log](https://0x0.st/XiMt.log)

after pressing the "build databases" it crashes with an empty white box while being frozen. This is what it added additionally to the logs.

```
[INFO][2024-04-06 15:45:21][55552][MainThread][main_content_panel][_do_build_database_thread][2664] : Opening file dialog to specify output file
[INFO][2024-04-06 15:45:26][55552][MainThread][main_content_panel][_do_build_database_thread][2673] : Selected path: C:\Users\Official Husko\AppData\Local\RimSort\test.json
[INFO][2024-04-06 15:45:26][55552][Dummy-10][wrapper][__init__][145] : Initializing DynamicQuery
[ERROR][2024-04-06 15:45:27][55552][Dummy-10][__main__][handle_exception][56] : The main application loop has failed with an uncaught exception
[INFO][2024-04-06 15:45:27][55552][Dummy-10][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
  File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\metadata.py", line 1906, in run
  File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 212, in create_steam_db
  File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 323, in IPublishedFileService_GetDetails
  File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 167, in call
  File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 309, in __call__
ValueError: Method requires 'admin_query' to be set
]
```

**Comment by twstagg** [comment] 2024-04-12 21:45
@Official-Husko 

I cannot reproduce the issue. Could you please provide more information regarding your path configuration for your Local mods? I would also like to know if you are able to reproduce the issue, and if so, could you please provide a log? You can find my log attached here from successfully (not destructively) cloning the same repo you did on the main branch:

[RimSort.log](https://github.com/RimSort/RimSort/files/14963823/RimSort.log)
![Screenshot from 2024-04-12 16-43-59](https://github.com/RimSort/RimSort/assets/2766946/6bf6c918-a61e-44ea-a97a-93dd295fb7d1)


@LionelColaso 

Could this be related to your changes around #263 ?

Related to transition to PyGit2?

@Chunnyluny 

`git.exe` is no longer a dependency for RimSort git-related actions. PyGit2 has been implemented instead of GitPython by @LionelColaso. We should not need git installed anymore because PyGit2 implements git directly via libgit2 bindings.

**Comment by Official-Husko** [comment] 2024-04-13 07:58
> @Official-Husko
> 
> I cannot reproduce the issue. Could you please provide more information regarding your path configuration for your Local mods? I would also like to know if you are able to reproduce the issue, and if so, could you please provide a log? You can find my log attached here from successfully (not destructively) cloning the same repo you did on the main branch:
> 
> [RimSort.log](https://github.com/RimSort/RimSort/files/14963823/RimSort.log) ![Screenshot from 2024-04-12 16-43-59](https://private-user-images.githubusercontent.com/2766946/322146881-6bf6c918-a61e-44ea-a97a-93dd295fb7d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTk0NDEsIm5iZiI6MTcxMjk1OTE0MSwicGF0aCI6Ii8yNzY2OTQ2LzMyMjE0Njg4MS02YmY2YzkxOC1hNjFlLTQ0ZWEtYTk3YS05M2RkMjk1ZmI3ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMjE1OTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZlZWQ3YjVmODhmYjMwMGZmN2VjYjE2OTQ1ZjY1ODgxODI2ODZhM2FkYTBmYmY1MzcwMmNhMmRjMjgzYzJjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aVHBXYAfX3wtxOM-nYss6jrHUstKaz1XL7jG6BVShbo)
> 
> @LionelColaso
> 
> Could this be related to your changes around #263 ?
> 
> Related to transition to PyGit2?
> 
> @Chunnyluny
> 
> `git.exe` is no longer a dependency for RimSort git-related actions. PyGit2 has been implemented instead of GitPython by @LionelColaso. We should not need git installed anymore because PyGit2 implements git directly via libgit2 bindings.

I will try to recreate it and share a log.

**Comment by BitCrack** [comment] 2024-04-20 02:15
> > > > Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish It will then also update if the repo gets updated on github. you can also find your old rimsort log too, which you can find in the upload logbutton/settingsbutton rimsort.old
> > > 
> > > 
> > > 
> > > 1. I do have git.exe.
> > > 2. Requiring Edge seems like a weird thing but i should have the latest webview which i guess is what it needs specifically.
> > > 3. I can only use GitHub links or did i understand that wrong?
> > 
> > 
> > ```
> > * 1 okay that is good
> > 
> > * 2 you misunderstood so I edited. I didn't mean Microsoft edge I mean edge build which is a prerelease term which is used in GitHub releases.
> > 
> > * 3 GitHub links idk about gitgud or gitbucket or anything beyond GitHub
> > ```
> 
> Here is what i can report right now after trying the edge build.
> 
> 1. RimWorld completely refuses to start up. Clicking run game does nothing while working on the latest stable release.
> 2. Using the Database Builder Crashes on both edge and stable.
> 
> [latest log](https://0x0.st/XiMt.log)
> 
> after pressing the "build databases" it crashes with an empty white box while being frozen. This is what it added additionally to the logs.
> 
> ```
> [INFO][2024-04-06 15:45:21][55552][MainThread][main_content_panel][_do_build_database_thread][2664] : Opening file dialog to specify output file
> [INFO][2024-04-06 15:45:26][55552][MainThread][main_content_panel][_do_build_database_thread][2673] : Selected path: C:\Users\Official Husko\AppData\Local\RimSort\test.json
> [INFO][2024-04-06 15:45:26][55552][Dummy-10][wrapper][__init__][145] : Initializing DynamicQuery
> [ERROR][2024-04-06 15:45:27][55552][Dummy-10][__main__][handle_exception][56] : The main application loop has failed with an uncaught exception
> [INFO][2024-04-06 15:45:27][55552][Dummy-10][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
>   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\metadata.py", line 1906, in run
>   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 212, in create_steam_db
>   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 323, in IPublishedFileService_GetDetails
>   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 167, in call
>   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 309, in __call__
> ValueError: Method requires 'admin_query' to be set
> ]
> ```

I'm getting the same error on edge as well.
```
[INFO][2024-04-20 04:06:14][10304][Dummy-29][wrapper][__init__][145] : Initializing DynamicQuery
[ERROR][2024-04-20 04:06:15][10304][Dummy-29][__main__][handle_exception][56] : The main application loop has failed with an uncaught exception
[INFO][2024-04-20 04:06:15][10304][Dummy-29][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
  File "G:\RimSort\app\utils\metadata.py", line 1927, in run
  File "G:\RimSort\app\utils\steam\webapi\wrapper.py", line 278, in pfids_by_appid
  File "G:\RimSort\app\utils\steam\webapi\wrapper.py", line 449, in IPublishedFileService_QueryFiles
  File "G:\RimSort\steam\webapi.py", line 167, in call
  File "G:\RimSort\steam\webapi.py", line 309, in __call__
ValueError: Method requires 'admin_query' to be set
]
```

**Comment by twstagg** [comment] 2024-04-20 03:01
> > > > > Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish It will then also update if the repo gets updated on github. you can also find your old rimsort log too, which you can find in the upload logbutton/settingsbutton rimsort.old
> > > > 
> > > > 
> > > > 
> > > > 1. I do have git.exe.
> > > > 2. Requiring Edge seems like a weird thing but i should have the latest webview which i guess is what it needs specifically.
> > > > 3. I can only use GitHub links or did i understand that wrong?
> > > 
> > > 
> > > ```
> > > * 1 okay that is good
> > > 
> > > * 2 you misunderstood so I edited. I didn't mean Microsoft edge I mean edge build which is a prerelease term which is used in GitHub releases.
> > > 
> > > * 3 GitHub links idk about gitgud or gitbucket or anything beyond GitHub
> > > ```
> > 
> > 
> > Here is what i can report right now after trying the edge build.
> > 
> > 1. RimWorld completely refuses to start up. Clicking run game does nothing while working on the latest stable release.
> > 2. Using the Database Builder Crashes on both edge and stable.
> > 
> > [latest log](https://0x0.st/XiMt.log)
> > after pressing the "build databases" it crashes with an empty white box while being frozen. This is what it added additionally to the logs.
> > ```
> > [INFO][2024-04-06 15:45:21][55552][MainThread][main_content_panel][_do_build_database_thread][2664] : Opening file dialog to specify output file
> > [INFO][2024-04-06 15:45:26][55552][MainThread][main_content_panel][_do_build_database_thread][2673] : Selected path: C:\Users\Official Husko\AppData\Local\RimSort\test.json
> > [INFO][2024-04-06 15:45:26][55552][Dummy-10][wrapper][__init__][145] : Initializing DynamicQuery
> > [ERROR][2024-04-06 15:45:27][55552][Dummy-10][__main__][handle_exception][56] : The main application loop has failed with an uncaught exception
> > [INFO][2024-04-06 15:45:27][55552][Dummy-10][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
> >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\metadata.py", line 1906, in run
> >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 212, in create_steam_db
> >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 323, in IPublishedFileService_GetDetails
> >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 167, in call
> >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 309, in __call__
> > ValueError: Method requires 'admin_query' to be set
> > ]
> > ```
> 
> I'm getting the same error on edge as well.
> 
> ```
> [INFO][2024-04-20 04:06:14][10304][Dummy-29][wrapper][__init__][145] : Initializing DynamicQuery
> [ERROR][2024-04-20 04:06:15][10304][Dummy-29][__main__][handle_exception][56] : The main application loop has failed with an uncaught exception
> [INFO][2024-04-20 04:06:15][10304][Dummy-29][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
>   File "G:\RimSort\app\utils\metadata.py", line 1927, in run
>   File "G:\RimSort\app\utils\steam\webapi\wrapper.py", line 278, in pfids_by_appid
>   File "G:\RimSort\app\utils\steam\webapi\wrapper.py", line 449, in IPublishedFileService_QueryFiles
>   File "G:\RimSort\steam\webapi.py", line 167, in call
>   File "G:\RimSort\steam\webapi.py", line 309, in __call__
> ValueError: Method requires 'admin_query' to be set
> ]
> ```

This will be fixed in the next release.

**Comment by Official-Husko** [comment] 2024-04-20 09:29
> > > > > > Do you know that you need git.exe to install GitHub mods ? You also need to have the latest edge from December, not the version from August 2023. I think you can only copy links directly from GitHub repos, for example https://github.com/bbradson/Performance-Fish It will then also update if the repo gets updated on github. you can also find your old rimsort log too, which you can find in the upload logbutton/settingsbutton rimsort.old
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. I do have git.exe.
> > > > > 2. Requiring Edge seems like a weird thing but i should have the latest webview which i guess is what it needs specifically.
> > > > > 3. I can only use GitHub links or did i understand that wrong?
> > > > 
> > > > 
> > > > ```
> > > > * 1 okay that is good
> > > > 
> > > > * 2 you misunderstood so I edited. I didn't mean Microsoft edge I mean edge build which is a prerelease term which is used in GitHub releases.
> > > > 
> > > > * 3 GitHub links idk about gitgud or gitbucket or anything beyond GitHub
> > > > ```
> > > 
> > > 
> > > Here is what i can report right now after trying the edge build.
> > > 
> > > 1. RimWorld completely refuses to start up. Clicking run game does nothing while working on the latest stable release.
> > > 2. Using the Database Builder Crashes on both edge and stable.
> > > 
> > > [latest log](https://0x0.st/XiMt.log)
> > > after pressing the "build databases" it crashes with an empty white box while being frozen. This is what it added additionally to the logs.
> > > ```
> > > [INFO][2024-04-06 15:45:21][55552][MainThread][main_content_panel][_do_build_database_thread][2664] : Opening file dialog to specify output file
> > > [INFO][2024-04-06 15:45:26][55552][MainThread][main_content_panel][_do_build_database_thread][2673] : Selected path: C:\Users\Official Husko\AppData\Local\RimSort\test.json
> > > [INFO][2024-04-06 15:45:26][55552][Dummy-10][wrapper][__init__][145] : Initializing DynamicQuery
> > > [ERROR][2024-04-06 15:45:27][55552][Dummy-10][__main__][handle_exception][56] : The main application loop has failed with an uncaught exception
> > > [INFO][2024-04-06 15:45:27][55552][Dummy-10][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
> > >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\metadata.py", line 1906, in run
> > >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 212, in create_steam_db
> > >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\app\utils\steam\webapi\wrapper.py", line 323, in IPublishedFileService_GetDetails
> > >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 167, in call
> > >   File "C:\PROGRA~2\Steam\STEAMA~1\common\RimWorld\RIMSOR~2\steam\webapi.py", line 309, in __call__
> > > ValueError: Method requires 'admin_query' to be set
> > > ]
> > > ```
> > 
> > 
> > I'm getting the same error on edge as well.
> > ```
> > [INFO][2024-04-20 04:06:14][10304][Dummy-29][wrapper][__init__][145] : Initializing DynamicQuery
> > [ERROR][2024-04-20 04:06:15][10304][Dummy-29][__main__][handle_exception][56] : The main application loop has failed with an uncaught exception
> > [INFO][2024-04-20 04:06:15][10304][Dummy-29][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
> >   File "G:\RimSort\app\utils\metadata.py", line 1927, in run
> >   File "G:\RimSort\app\utils\steam\webapi\wrapper.py", line 278, in pfids_by_appid
> >   File "G:\RimSort\app\utils\steam\webapi\wrapper.py", line 449, in IPublishedFileService_QueryFiles
> >   File "G:\RimSort\steam\webapi.py", line 167, in call
> >   File "G:\RimSort\steam\webapi.py", line 309, in __call__
> > ValueError: Method requires 'admin_query' to be set
> > ]
> > ```
> 
> This will be fixed in the next release.

I'm sorry i haven't sent any logs or further messages. i had no time to play rimworld or test things with rimsort since i got really busy with other things especially family stuff.

**Comment by twstagg** [comment] 2024-04-25 13:15
Hi @Official-Husko 

Is this still an issue on the latest build? We have reverted from pygit2 to gitpython so we can address issues with the implementation. You will need git proper to be installed on your system and available in your $PATH

**Comment by Official-Husko** [comment] 2024-04-25 13:32
> Hi @Official-Husko
> 
> Is this still an issue on the latest build? We have reverted from pygit2 to gitpython so we can address issues with the implementation. You will need git proper to be installed on your system and available in your $PATH

I have tested the latest build and it no longer deleted everything to throw the loose files inside. The Destructive git clone seems to be resolved.

**Closed** 2024-04-27 00:23 UTC
Labels: bugs 🪲, Windows 🪟, third party 📲
