### ISSUE TITLE
FIXME: When extracting, Windows Defender pops up a warning window: PUA /Puwaders.C!ml.

### ISSUE THREAD

**Issue by windicevista** [RimSort/RimSort#524] opened 2024-07-22 17:28 UTC
**Describe the bug:**
There was no issue when extracting version 1.0.8. However, while extracting the latest version 1.0.9, a warning message pops up, and the file is quarantined before it can be executed.

Is this a false positive as well?

**Screenshots:**
![image](https://github.com/user-attachments/assets/f5a43198-c9b8-40ba-b78d-168ece854ee5)

**Please complete the following information:**

- Operating System:Windows 10
- Processor Architecture: x86

**Comment by hk21702** [comment] 2024-07-22 18:01
It's a false positive and can be safely override. Known issue with the latest release. I've already made a ticket with Microsoft to fix it.

1.0.8 actually had the same issue but was resolved. Unfortunately compiled python often has this issue with false positives. New release, new hash, so need to go through the process again.

Will close once the issue is resolved with this release.

**Comment by hk21702** [comment] 2024-07-25 15:28
Just confirming, is this still and issue? Virus total no longer shows Microsoft as a detection.

**Comment by windicevista** [comment] 2024-07-25 15:54
OK, it can be used normally now. Thank you.

**Closed** 2024-07-25 15:56 UTC
