### ISSUE TITLE
FIXME: symbol lookup error in Linux on Wayland

### ISSUE THREAD

**Issue by jcstryker** [RimSort/RimSort#127] opened 2023-06-27 21:41 UTC
**Describe the bug**

Getting the following error message when running in a GNOME wayland session on linux

```
./RimSort.bin: symbol lookup error: /opt/rimsort/PySide6/qt-plugins/platforms/../../../libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags
```

**To Reproduce**
1. Run Arch Linux with a Wayland graphical session
2. Execute rimsort in terminal

**Expected behavior**

Rimsort should launch or provide a help screen

**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/6476501/c4753046-e115-49be-b13c-5cd83e1fa651)

**Please complete the following information:**
 - OS: Arch Linux
 - RimSort version: alpha_v1.0.5.4-1
 - Please provide a `RimSort.log`:
 N/A
 - Are you running from Python interpreter or from a compiled RimSort release?
 AUR Package - compiled releas

**Additional context**

**Comment by twstagg** [comment] 2023-06-27 21:54
@jcstryker Can you reproduce using the latest version? We are currently on alpha-1.0.5.5

**Comment by twstagg** [comment] 2023-06-27 22:40
Heh, I cannot even run RimSort on Wayland in my Debian 11 environment:

![image](https://github.com/RimSort/RimSort/assets/2766946/31cd89b4-9d90-4bb8-b93c-beb8e8514efd)

https://bugreports.qt.io/browse/QTBUG-114635

**Comment by twstagg** [comment] 2023-06-27 23:07
@jcstryker Here is a fixed build: https://github.com/RimSort/RimSort/releases/tag/alpha-v1.0.5.5-wayland

I will keep this issue in mind for future builds. @jtljac over on #35 is who maintains the AUR package - maybe give a shout to them so they can update their AUR package.

**Comment by jcstryker** [comment] 2023-06-27 23:58
@twstagg much appreciated I can confirm this works and @jtljac I was able to install this by modifying the source file in your PKGBUILD

thank you both for your work

**Comment by jtljac** [comment] 2023-06-27 23:59
I'm a little wary of making a new AUR release for this hotfix since it's a pre-release and the release is in a slightly different format.
Is it possible this could be a full release with the file as `RimSort-Alpha-v1.0.5.x_Linux_x86_64.zip`?

**Comment by twstagg** [comment] 2023-06-28 00:33
> I'm a little wary of making a new AUR release for this hotfix since it's a pre-release and the release is in a slightly different format. Is it possible this could be a full release with the file as `RimSort-Alpha-v1.0.5.x_Linux_x86_64.zip`?

You don't have to make a release for this hotfix, unless you want to. The next release will have the same format as before.

**Comment by twstagg** [comment] 2023-10-02 22:00
@YoteZip Can you try the 

> @twstagg
> 
> Just a note, I am still running into this issue (or maybe a related issue) on Debian 12.1 w/ Wayland. The `1.0.5.5-wayland` build does work for me, but `1.0.6.2-hf`, `1.0.6.2`, `1.0.6.1`, and `1.0.6.0` all display the following error:
> 
> ```
> ./RimSort.bin: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags
> ```

Could you please try the Edge 6bc03c2 build and confirm if the issue is resolved or not?

**Comment by YoteZip** [comment] 2023-10-02 22:32
> @YoteZip Can you try the
> 
> > @twstagg
> > Just a note, I am still running into this issue (or maybe a related issue) on Debian 12.1 w/ Wayland. The `1.0.5.5-wayland` build does work for me, but `1.0.6.2-hf`, `1.0.6.2`, `1.0.6.1`, and `1.0.6.0` all display the following error:
> > ```
> > ./RimSort.bin: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags
> > ```
> 
> Could you please try the Edge [6bc03c2](https://github.com/RimSort/RimSort/commit/6bc03c2c54911994db4f099551da1f25b034fca0) build and confirm if the issue is resolved or not?

I grabbed the build from [here](https://github.com/RimSort/RimSort/releases/tag/Edge) and am still getting the following error on Debian 12.1, Mesa 22.3.6
`./RimSort.bin: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags`

**Comment by twstagg** [comment] 2023-10-02 22:33
Thanks

**Comment by twstagg** [comment] 2023-10-11 23:05
@YoteZip Can you test the latest Edge build (402a9b9)

**Comment by YoteZip** [comment] 2023-10-11 23:07
> @YoteZip Can you test the latest Edge build ([402a9b9](https://github.com/RimSort/RimSort/commit/402a9b9ffbebc180fe6601a773b64f5a4a32bc6a))

Same issue

**Comment by twstagg** [comment] 2024-04-27 00:26
@YoteZip Sorry for my delay. This one is really an issue that will require some sort of long-term solution that maybe targets more than one Linux distro.

**Comment by twstagg** [comment] 2024-04-27 00:27
Didn't mean to close!

**Comment by Chunnyluny** [comment] 2024-04-27 15:04
@jcstryker @jtljac @YoteZip 
Will be fixed in another overall effort for Linux compatibility. Closing as duplicate of #35

**Closed by Chunnyluny** 2024-04-27 15:04 UTC
Labels: bugs 🪲, Linux🐧
