### ISSUE TITLE
FIXME: Crash when opening a menu that asks for a directory

### ISSUE THREAD

**Issue by AludisNHG** [RimSort/RimSort#241] opened 2023-12-19 04:17 UTC
**Describe the bug**
Opening a menu that asks you to select a directory, for example "import modlist" causes a crash

**To Reproduce**
1. Go to 'RimSort'
2. Click on 'Import Mod List'
3. See error

**Expected behavior**
A menu should open telling you to select a directory

**Please complete the following information:**
 - OS: [Arch Linux]
 - RimSort version: Alpha-v1.0.6.2-hf
 - Please provide a [RimSort.log](https://github.com/RimSort/RimSort/files/13711089/RimSort.log):
 - It's the compiled version from the Release tab

**Comment by Chunnyluny** [comment] 2023-12-19 15:35
If it is the august version, you should use the latest edge prebuild, we are working on fixing a lot of options and functions. Can you try the latest edge from November please and check if you still got a crash ?

**Comment by AludisNHG** [comment] 2023-12-19 20:21
I tried, however that one doesn't even open.
Here's the console
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, eglfs, xcb, minimalegl, wayland, vnc, minimal, linuxfb, vkkhrdisplay, offscreen.
```

**Comment by AludisNHG** [comment] 2023-12-19 20:32
I should probably add that reinstalling the application didn't fix this problem

**Comment by Chunnyluny** [comment] 2024-04-27 15:10
@AludisNHG Will be fixed in another overall effort for Linux compatibility. Closing as duplicate of #35

**Closed by Chunnyluny** 2024-04-27 15:10 UTC
Labels: bugs 🪲, Linux🐧
